### PR TITLE
New Feature: Win Difference Threshold (Aka Auto Golden Cap)

### PR DESCRIPTION
**Pull request by Shigbeard**
# What is this?

A new feature to the improved match timer, that allows for leagues to selectively disable part of it's features for their leagues. This is used at the moment by Ozfortress (@coreobs) for their lower divisions. However, I've taken consideration for leagues that do not wish to use this new feature, and ensured that default behavior remains unchanged (That is, you must intentionally use the new convars to enable this new feature).

# What does it do

Instantly(*) ends the game upon the conclusion of the match timer based on the difference between the round wins of both teams. Configured using the `mp_timelimit_improved_threshold` convar, by setting this to any value above -1, we're able to set a threshold for `RED_SCORE minus BLU_SCORE`, where should it be higher than the value defined by this convar, we immediately end the game. Should it be equal or lower, we go into endless overtime as previously defined by this plugin.

The way this is calculated is simple. At the end of the match timer, I've added an [extra code block](addons/sourcemod/scripting/improved_match_timer.sp#L138) - we capture the integer value (live, mind you, not cached) and compare it to `intAbs(GetTeamScore(2) - GetTeamScore(3))`. `intabs()` is a function I've added which will return the absolute value of any given integer (effecitvely, checks if its below 0, and if it is, multiplies it by -1, making it positive).

If that difference is equal to, or less than the threshold set by the aforementioned convar, nothing happens, the plugin continues as normal. Otherwise, we destroy the timer handle that we were using to track the match time, and we stop the plugin from activating infinite overtime, allowing the game to end.

# How does this effect existing leagues?

It shouldn't! We set the default value to "-1", which skips our code block entirely that ends the match. Inattentive leagues should be able to just operate as-is with no difference. However as a safety precaution they should update their configs to add `mp_timelimit_improved_threshold X` where X is the highest win difference your players will be able to accomplish under your ruleset, or even higher.

That said, I don't expect this to be merged without thorough testing by the major leagues such as RGL, EUTF2L, and Asia Fortress. Ozfortress has already been using it for a while (@coreobs to confirm), infact they requested these changes.

(*) - By instantly, I mean in accordance with how TF2 normally operates. Where the Pro Ruleset Timer would normally change the time limit and the win difference to activate effectively an endless overtime, we instead bypass that logic and allow TF2 to end the game as it normally would.

### CODE REVIEW

**Comment by Shigbeard** [comment]
Force push to squash compile only commit into 544b34f

**Comment by dewbsku** [comment]
Greetings,

I appreciate the work you put into this feature and the use it has found in some leagues.

The purpose of this plugin is to eliminate timer related strategies that encourage passive gameplay for the winning team. We believe that this feature goes against that purpose. For that reason, we will not accept this feature into the plugin.

I encourage you to continue using your fork, but please consider renaming the plugin (the .sp and .smx files) as they serve different purposes.

**Comment by Shigbeard** [comment]
>The purpose of this plugin is to eliminate timer related strategies that encourage passive gameplay for the winning team.

I understand this, however I've found that in doing so, you've enabled teams to delay tightly scheduled tournaments such as LANs and One-Night tournaments simply by either running the game to a large advantage and then forcing the enemy team to slowly make up for that advantage, or by simply being evenly matched after a slow warmup for one team.

That said, the default nature of my changes means that absolutely nothing changes in functionality with the plugin. Timer related strategies remains eliminated, and the endless nature of games past match timer for evenly matched (or even intentionally sabotaging) teams remains in play. A league must INTENTIONALLY chose to enforce these functionalities up to a certain threshold

I usually recommend 1 or 2 score threshold - if a game is 2-1 or 3-1 the winning team still cant afford to park the bus because if the losing team suddenly finds their momentum, that momentum is allowed to carry over beyond the match timer all the same.

Functionally, my feature does not go against that purpose.

Now, the main reason I wanted this feature merged into the mainstream plugin is that services like serveme.tf use a standard image for all TF2 competitive leagues, and while renaming my fork would prevent my fork from being overwritten by your fork, it would still result in additional overhead where leagues that wish to use this fork would need to poke and prod at Arie to include my fork, and then modify their configs to disable your fork on the fly. Then the implication there would be that other leagues would need to adjust their configs to ensure this version of the plugin is loaded instead of my fork.

With that behavior in mind, and my intention to ensure feature parity with any future changes of your version, service providers will likely decide to simply side with the fork with the most features.

Again, I urge you to reconsider your decision to not merge these changes. They will not impact existing leagues, and only serve to add new functionality to the minority of leagues looking to utilize these new features.

**Comment by dewbsku** [comment]
We do not endorse this feature, and therefore we will not include it in the original plugin.

**Comment by Shigbeard** [comment]
Very well. If you will not accept this feature, despite it clearly introducing _**no changing functionality for leagues that do not wish to use it**_, then I will simply maintain my own fork of it.

Do note, my fork will be designed to disable your plugin should it find itself running on the same server. This is not out of malicious intent, it is merely to ensure that the two plugins do not conflict with one another.

**Pull request closed without merging**
